# -*- coding: utf-8 -*-
"""Emit doc/the-pass.html and doc/the-pass.zh.html from one geometry.

    python3 scripts/the-pass.py

Both pages are self-contained by the rule architecture.html states of itself:
no build, no assets, no script. That rule is about the *published* file, and it
is what makes a hand-maintained pair go wrong — architecture.html and its
Chinese twin are 61KB each and drift is caught by nobody. So here the geometry
is written once, the words are written twice in EN and ZH below it, and neither
HTML file is edited by hand. Changing the drawing means changing this file and
running it.

The style block is read out of doc/architecture.html rather than copied, so the
two pages cannot fall out of the same design system either.
"""
import pathlib

ARCH = (pathlib.Path(__file__).resolve().parent.parent / "doc/architecture.html").read_text()
STYLE = ARCH[ARCH.index("<style>"):ARCH.index("</style>") + len("</style>")]

# the page adds two things architecture.html has no use for
EXTRA_CSS = """
<style>
.banner{background:#fdf6e3;border:1px solid #c9a227;border-left-width:4px;
  border-radius:4px;padding:.7rem .9rem;margin:.6rem 0 1.1rem;font-size:.86rem;
  line-height:1.55;color:#4a3c14}
.banner a{color:#7a5c0e}
@media (prefers-color-scheme:dark){
  .banner{background:#2a2517;border-color:#8a6a2e;color:#e6dcc0}
  .banner a{color:#e9c96a}
}
  pre.code {
    margin: 26px 0 0;
    background: var(--raised);
    border: 1px solid var(--rule);
    border-left: 3px solid var(--flow);
    padding: 16px 20px;
    overflow-x: auto;
    font-family: var(--f-mono);
    font-size: 13.5px;
    line-height: 1.7;
  }
  pre.code .c { color: var(--faint); }
  pre.code b { color: var(--flow); font-weight: 500; }
</style>
"""

MONO = 'font-family="IBM Plex Mono, monospace"'

def marker():
    return ('<defs><marker id="ar" viewBox="0 0 10 10" refX="9" refY="5" '
            'markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
            '<path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor"/></marker></defs>')

def box(x, y, w, h, *, stroke="currentColor", var=None, sw=1, dash=None, op=None):
    s = f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="none" stroke="{stroke}"'
    if var:
        s += f' style="stroke:var(--{var})"'
    s += f' stroke-width="{sw}"'
    if dash:
        s += f' stroke-dasharray="{dash}"'
    if op:
        s += f' opacity="{op}"'
    return s + "/>"

def txt(x, y, t, *, size=12.5, anchor="middle", mono=False, var=None, op=None,
        ls=None, weight=None, transform=None):
    s = f'<text x="{x}" y="{y}" text-anchor="{anchor}" font-size="{size}"'
    if mono:
        s += " " + MONO
    s += ' fill="currentColor"'
    if var:
        s += f' style="fill:var(--{var})"'
    if op:
        s += f' opacity="{op}"'
    if ls:
        s += f' letter-spacing="{ls}"'
    if weight:
        s += f' font-weight="{weight}"'
    if transform:
        s += f' transform="{transform}"'
    return s + f">{t}</text>"

def line(x1, y1, x2, y2, *, arrow=True, op=".55", var=None, dash=None, sw=1):
    s = f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="currentColor"'
    if var:
        s += f' style="stroke:var(--{var})"'
    s += f' stroke-width="{sw}" opacity="{op}"'
    if dash:
        s += f' stroke-dasharray="{dash}"'
    if arrow:
        s += ' marker-end="url(#ar)"'
    return s + "/>"

def poly(pts, *, arrow=True, op=".55", var=None):
    p = " ".join(f"{a},{b}" for a, b in pts)
    s = f'<polyline points="{p}" fill="none" stroke="currentColor"'
    if var:
        s += f' style="stroke:var(--{var})"'
    s += f' stroke-width="1" opacity="{op}"'
    if arrow:
        s += ' marker-end="url(#ar)"'
    return s + "/>"


# ------------------------------------------------------------------- the words
# Written for somebody who is about to point Lingtai at a repository, not for
# somebody reconciling it with its own history. No ADR archaeology, no
# before-and-after: what the pipeline is, what each word means, what is yours to
# set, and where a ticket goes when a step will not let it past.

EN = dict(
    lang="en", otherlang="\u4e2d\u6587",
    comment="Generated by scripts/the-pass.py — edit that, not this.",
    title="A pass, step by step — Lingtai",
    eyebrow="Lingtai · 灵台 — one ticket, from the queue to merged",
    h1="How one ticket gets built",
    sub="Lingtai takes one ticket at a time and walks it through ten steps. "
        "This page is what each step is, what you decide about it, and where a "
        "ticket goes when a step will not let it past.",
    th1="<b>The pipeline is fixed; what each step <i>does</i> is yours.</b> The "
        "ten steps and their order never change — that is what makes the board, "
        "the log and this page describe one thing. What runs at each step is a "
        "<b>plugin</b>, and your recipe names it. Say nothing and you get the "
        "set Lingtai ships, which is a working pipeline.",
    th2="<b>One worktree is the whole of a pass.</b> A ticket gets a branch cut "
        "from your base, and everything after that — the install, the agent, the "
        "build, the review, the merge — happens in it. Nothing is thrown away "
        "and restarted because a step said no.",

    s1h="The ten steps",
    s1l="Read it downward. The four in brass are the steps that may say no; "
        "everything that does not simply pass arrives at <code>proposed</code>, "
        "which is the only step that decides what happens next.",
    s1c="<b>Brass means a step may refuse</b> — <code>prepared</code>, "
        "<code>build</code>, <code>proposed</code> and <code>merge</code>. The "
        "dashed rectangle is the worktree: cut at <code>admit</code>, alive until "
        "the merge is done. The dashed lines on the right are every step that did "
        "not simply pass; they all arrive at <code>proposed</code>. The solid "
        "lines on the left are what <code>proposed</code> answers — back to the "
        "agent, back to the queue, or to you.",

    s2h="Every word on that drawing",
    s2l="Nine terms, and Lingtai means exactly these by them.",
    th_what="term", th_who="what it means", th_crit="where you meet it",
    tbl=[
      ("step", "One of the ten. The sequence is fixed and so are the names.",
       "the board's rail, and <code>steps:</code> in your recipe"),
      ("plugin", "The thing that runs at a step — a command, an agent, a "
       "worktree, a merge. Swap it and the step does something else.",
       "each entry under a step"),
      ("refuse", "A step's verdict that <i>this change is not right</i>. It "
       "costs: it sends the work back to the agent and spends one round.",
       "the card says which step refused, and why"),
      ("did not finish", "The step stopped without judging — the agent asked a "
       "question, a reviewer crashed. <b>Not a refusal, and it buys no round.</b>",
       "the same place, with a different reason"),
      ("reason", "A short machine-readable word that travels with a refusal, so "
       "<code>proposed</code> can route on it and you can read it later.",
       "on the card, and on the log"),
      ("round", "One more go at the same worktree, carrying what refused it. "
       "<code>rounds</code> is how many you will pay for.",
       "<code>implement:</code> in your recipe"),
      ("restart", "The ticket is released back to the queue and started over "
       "from the base. Another ticket may be taken first.",
       "<code>claim:</code> in your recipe"),
      ("worktree", "The branch and working copy this pass owns. One per pass; "
       "the agent cannot see outside it.",
       "cut at <code>admit</code>, named on the card"),
      ("waiting on you", "The one place a ticket stops for a person. Only "
       "<code>proposed</code> can put it there.",
       "the board's top row"),
    ],

    s3h="What you write",
    s3l="One file, on your machine, at <code>~/.lingtai/&lt;project&gt;/recipe.yml</code>. "
        "Nothing is committed to the repository Lingtai works on.",
    s3p="<b>A step is a list of plugins, and they run in the order you write "
        "them.</b> What the step does with the results is the step's own "
        "business: at <code>claim</code> the first plugin that finds a ticket "
        "wins; at <code>prepared</code> every one of them has to pass. A step you "
        "leave out of the file simply has nothing at it — and is still drawn, so "
        "that <i>nothing configured</i> and <i>silently skipped</i> never look "
        "alike.",
    s3p2="<b>Some keys are not the plugin's — they are the bounds Lingtai puts "
         "on it.</b> A <code>run:</code> plugin cannot ignore its "
         "<code>timeout</code>, because the runner enforces it rather than the "
         "plugin honouring it. <code>rounds</code> and <code>restarts</code> work "
         "the same way, and each sits on the step it bounds.",

    s4h="What a pass can cost you",
    s4l="Four numbers, and the first three are multiplied by the fourth.",
    c_turns="# inside one agent run",
    c_wall="# inside one agent run",
    c_rounds="# how many times a refusal sends the agent back",
    c_restarts="# how many times this ticket may be claimed",
    s4p="Read it as arithmetic: one pass is up to <code>rounds + 1</code> agent "
        "runs, each bounded by <code>turns</code> and <code>wall</code> — and "
        "<code>restarts</code> is how many passes one ticket may buy. "
        "<code>lingtai add</code> prints the whole sum before anything runs.",
    s4p2="<b>Nothing here bounds what you are asked.</b> A step that did not "
         "finish — an agent that stopped to ask, a reviewer that crashed — buys "
         "no round, because it passed no judgement on your change.",

    s5h="When it stops and waits for you",
    s5l="One way in, and one place to look.",
    prop_h="What puts a ticket there",
    prop1="Every ceiling is spent — the rounds, then the restarts — and the "
          "change is still refused. Or a question came back that only you can "
          "answer: an unclear requirement, a design decision, two changes that "
          "edited the same intent differently.",
    prop2="<b>Only <code>proposed</code> can send a ticket to you.</b> No step "
          "reaches you on its own, which is what makes <i>is this worth "
          "interrupting somebody over</i> one decision in one place rather than "
          "a habit scattered through the pipeline.",
    gap_h="What it carries with it",
    gap1="What refused it and why, in the words the step used — the findings, "
         "the build's output, the paths that conflicted. You should never have "
         "to open a log to learn why a ticket is waiting.",
    gap2="And <code>end</code> still runs. Closing the ticket yourself is an "
         "outcome like any other, and the step that tidies up runs on every "
         "outcome rather than only on the happy one.",

    foot="Generated from scripts/the-pass.py · Lingtai",
    f1_alt="One pass from claim to end. Ten steps on a spine; four of them may "
           "refuse — prepared, build, proposed and merge — and every step that "
           "did not simply pass arrives at proposed, which is the only step "
           "that routes and the only way to waiting on you.",
    f1_steps=(
        ("claim",     "which tickets, and in what order",           False),
        ("admit",     "the requirement · the worktree",             False),
        ("prepared",  "install · is the base green?",               True),
        ("design",    "a document, or none — either is an answer",  False),
        ("implement", "one agent, in that worktree",                False),
        ("build",     "typecheck · the unit suite",                 True),
        ("review",    "findings, and no verdict",                   False),
        ("proposed",  "the only step that decides what is next",    True),
        ("merge",     "the base in, verify, the base out",          True),
        ("end",       "close · labels · runs on every outcome",     False),
    ),
    f1_scope="THE WORKTREE · CUT AT ADMIT, ALIVE UNTIL THE MERGE IS DONE",
    f1_fan="a step that did not pass",
    f1_fan2="refused, or did not finish — carrying its reason",
    f1_ret1="and proposed answers",
    f1_ret_build="a conflict",
    f1_ret_impl="× rounds",
    f1_ret_claim="× restarts",
    f1_wait="waiting on you",
    f1_wait2="every ceiling spent · a question only you can answer",
    f1_spent="the one way in",
    f1_closed="you close it",
)

ZH = dict(
    lang="zh-Hans", otherlang="English",
    comment="由 scripts/the-pass.py 生成 —— 要改请改那个文件，不要改这个。",
    title="一趟 pass，一步一步 — 灵台",
    eyebrow="Lingtai · 灵台 —— 一张票，从队列到合并",
    h1="一张票是怎么被做出来的",
    sub="灵台一次只拿一张票，让它走完十步。这一页讲的是：每一步是什么、"
        "关于它你能决定什么、以及当某一步不放行时这张票去哪里。",
    th1="<b>流水线是固定的；每一步<i>做什么</i>是你的。</b>十步和它们的顺序永远不变 "
        "—— 正是这一点让看板、日志和这一页说的是同一件事。每一步跑什么，是一个"
        "<b>插件</b>，由你的 recipe 指定。什么都不写，你得到灵台自带的那一套，"
        "而那本身就是一条能用的流水线。",
    th2="<b>一棵工作树就是一趟 pass 的全部。</b>一张票拿到一个从你的 base 切出来的"
        "分支，之后的一切 —— install、agent、build、review、合并 —— 都发生在里面。"
        "不会因为某一步说了不，就把它扔掉重来。",

    s1h="十步",
    s1l="从上往下读。黄铜色的四步是会说不的；每一个没有径直通过的步都抵达 "
        "<code>proposed</code>，它是唯一决定下一步去哪的步。",
    s1c="<b>黄铜色表示这一步会拒绝</b> —— <code>prepared</code>、<code>build</code>、"
        "<code>proposed</code>、<code>merge</code>。虚线框是工作树：在 "
        "<code>admit</code> 切出，一直活到合并完成。右边的虚线是每一个没有径直通过"
        "的步，它们全都抵达 <code>proposed</code>。左边的实线是 "
        "<code>proposed</code> 的回答 —— 回到 agent、回到队列，或者到你这里。",

    s2h="图上每一个词",
    s2l="九个词，灵台说它们时就是这个意思。",
    th_what="词", th_who="它是什么", th_crit="你在哪儿会碰到它",
    tbl=[
      ("step 步", "十步之一。顺序是固定的，名字也是。",
       "看板上的那条轨，以及 recipe 里的 <code>steps:</code>"),
      ("plugin 插件", "在某一步上跑的那个东西 —— 一条命令、一个 agent、一棵工作树、"
       "一次合并。换掉它，这一步就做别的事。", "某一步下面的每一条"),
      ("refuse 拒绝", "某一步给出的裁决：<i>这次改动不对</i>。它要花钱："
       "把活打回 agent，并花掉一轮。", "卡片上会写是哪一步拒的、为什么"),
      ("did not finish 没跑完", "这一步停了，但没有做出裁决 —— agent 问了个问题、"
       "reviewer 崩了。<b>这不是拒绝，它不买任何一轮。</b>",
       "同一个地方，只是 reason 不同"),
      ("reason 理由", "跟着拒绝一起走的一个机器可读的短词，"
       "好让 <code>proposed</code> 据它路由，也好让你事后读得懂。",
       "卡片上，以及日志上"),
      ("round 轮", "在同一棵工作树上再来一次，带着拒绝它的那些东西。"
       "<code>rounds</code> 是你愿意为几轮付钱。", "recipe 里的 <code>implement:</code>"),
      ("restart 重来", "这张票被放回队列，从 base 重新开始。"
       "队列可能会先拿走别的票。", "recipe 里的 <code>claim:</code>"),
      ("worktree 工作树", "这趟 pass 独占的分支和工作副本。一趟一棵；"
       "agent 看不到它之外的任何东西。", "在 <code>admit</code> 切出，卡片上有它的名字"),
      ("waiting on you", "一张票为了人而停下的唯一地方。"
       "只有 <code>proposed</code> 能把它放到那里。", "看板最上面那一行"),
    ],

    s3h="你要写的东西",
    s3l="一个文件，在你自己的机器上：<code>~/.lingtai/&lt;项目&gt;/recipe.yml</code>。"
        "灵台工作的那个仓库里，什么都不用提交。",
    s3p="<b>一步是一串插件，按你写下的顺序跑。</b>结果怎么归并，是那一步自己的事："
        "在 <code>claim</code>，第一个找到票的插件赢；在 <code>prepared</code>，"
        "每一个都得过。文件里没写的步，就是那一步上什么都没有 —— 而它仍然会被画出来，"
        "好让<i>没配置</i>和<i>被悄悄跳过</i>永远不长得一样。",
    s3p2="<b>有些键不属于插件 —— 它们是灵台加在插件上的界限。</b>一个 "
         "<code>run:</code> 插件没法忽略自己的 <code>timeout</code>，"
         "因为执行它的是 runner，不是插件在自觉遵守。<code>rounds</code> 和 "
         "<code>restarts</code> 是同一类，而且各自写在被它约束的那一步上。",

    s4h="一趟 pass 最多花你多少",
    s4l="四个数，前三个会被第四个乘一遍。",
    c_turns="# 一次 agent run 之内",
    c_wall="# 一次 agent run 之内",
    c_rounds="# 一次拒绝把 agent 打回去几次",
    c_restarts="# 这张票最多被认领几次",
    s4p="把它当算术读：一趟 pass 最多 <code>rounds + 1</code> 次 agent run，"
        "每次由 <code>turns</code> 和 <code>wall</code> 封顶 —— 而 "
        "<code>restarts</code> 是一张票最多买几趟 pass。"
        "<code>lingtai add</code> 会在任何东西跑起来之前把这笔总账打印给你。",
    s4p2="<b>这里没有任何一个数在限制「你被问几次」。</b>一个没跑完的步 —— "
         "agent 停下来问、reviewer 崩了 —— 不买任何一轮，"
         "因为它对你的改动没有做出任何裁决。",

    s5h="它什么时候停下来等你",
    s5l="一个入口，一个去处。",
    prop_h="什么会把一张票放到那里",
    prop1="所有上限都花完了 —— 先是 rounds，然后是 restarts —— 而这次改动仍然被拒。"
          "或者回来了一个只有你能回答的问题：需求不清、一个设计决定、"
          "两处改动把同一个意图改成了不同的样子。",
    prop2="<b>只有 <code>proposed</code> 能把票送到你面前。</b>没有任何一步能自己"
          "走到你这里 —— 正是这一点，让<i>这值不值得打扰一个人</i>成为一个地方的"
          "一个决定，而不是散落在整条流水线里的习惯。",
    gap_h="它会带着什么过来",
    gap1="是什么拒的、为什么，用那一步自己的话 —— findings、build 的输出、"
         "冲突的那些路径。你不该为了搞清一张票为什么在等而去翻日志。",
    gap2="而且 <code>end</code> 照样会跑。你自己把票关掉，也是一种结局；"
         "那个负责收尾的步对每一种结局都跑，而不是只对顺利的那一种。",

    foot="由 scripts/the-pass.py 生成 · 灵台",
    f1_alt="一趟 pass，从 claim 到 end。主干上十步，其中四步会拒绝 —— prepared、"
           "build、proposed、merge —— 而每一个没有径直通过的步都抵达 proposed，"
           "它是唯一做路由的一步，也是通向 waiting on you 的唯一入口。",
    f1_steps=(
        ("claim",     "取哪些票，按什么顺序",                        False),
        ("admit",     "需求 · 工作树",                              False),
        ("prepared",  "install · base 是绿的吗？",                  True),
        ("design",    "一份文档，或者没有 —— 都是回答",             False),
        ("implement", "一个 agent，在那棵工作树里",                  False),
        ("build",     "typecheck · 单元测试",                       True),
        ("review",    "交 findings，不做裁决",                      False),
        ("proposed",  "唯一决定下一步去哪的步",                      True),
        ("merge",     "base 并进来、verify、再合出去",               True),
        ("end",       "close · labels · 每一种结局都会跑到它",       False),
    ),
    f1_scope="工作树 · 在 ADMIT 切出，一直活到合并完成",
    f1_fan="一个没有径直通过的步",
    f1_fan2="被拒绝，或者没跑完 —— 带着它的 reason",
    f1_ret1="然后由 proposed 作答",
    f1_ret_build="解掉的冲突",
    f1_ret_impl="× rounds",
    f1_ret_claim="× restarts",
    f1_wait="waiting on you",
    f1_wait2="上限花完 · 一个只有你能回答的问题",
    f1_spent="唯一的入口",
    f1_closed="你把它关掉",
)


# ---------------------------------------------------------------- figure one
# Ten steps, and the geometry is computed from the list rather than typed.
# Hand-placed coordinates were fine for five; at ten they are a source of
# defects that no test would catch.
BX, BW = 270, 340              # the spine
CX = BX + BW / 2
TOP, PITCH, BH = 30, 78, 46    # first step, step-to-step, box height
RET = 176                      # proposed's returns, to the left of the scope
FAN = 648                      # what did not pass, to the right of the spine
RX, RW = 706, 226              # waiting on you, outside the worktree

def _y(i):
    return TOP + i * PITCH

def figure_one(T):
    o = [marker()]
    a = o.append
    steps = T["f1_steps"]                       # (name, under, refuses)
    n = len(steps)
    bottom = _y(n - 1) + BH

    # the worktree's scope: cut at admit, alive past the merge lane
    a(box(BX - 58, _y(1) - 12, BW + 116, _y(n - 2) + BH + 12 - (_y(1) - 12),
          var="prop", sw=2, dash="7 5"))
    a(txt(BX - 58, _y(1) - 18, T["f1_scope"], size=10.5, mono=True,
          anchor="start", var="prop", ls="1.3"))

    for i, (name, under, refuses) in enumerate(steps):
        y = _y(i)
        strong = name == "implement"
        a(box(BX, y, BW, BH, var="brass" if refuses else None,
              sw=2.5 if strong else (2 if refuses else 1.5)))
        a(txt(BX + 14, y + 20, "%d/%d" % (i + 1, n), size=11, mono=True,
              anchor="start", var="brass" if refuses else "faint", ls="1.2"))
        a(txt(CX, y + 20, name, size=13.5 if strong else 13, mono=True,
              var="brass" if refuses else None))
        a(txt(CX, y + 37, under, size=11.5, op=".62"))
        if i + 1 < n:
            a(line(CX, y + BH, CX, _y(i + 1)))

    # what did not pass: a stub from each such step into one channel, and one
    # arrow into proposed. Seven edges drawn as seven stubs and a rule.
    idx = {name: k for k, (name, _, _) in enumerate(steps)}
    po = idx["proposed"]
    for name in ("admit", "prepared", "design", "implement", "build", "review"):
        y = _y(idx[name]) + BH / 2
        a(line(BX + BW, y, FAN, y, arrow=False, op=".55", dash="4 4"))
    a(line(BX + BW, _y(idx["merge"]) + BH / 2, FAN,
           _y(idx["merge"]) + BH / 2, arrow=False, op=".55", dash="4 4"))
    a(line(FAN, _y(idx["admit"]) + BH / 2, FAN, _y(idx["merge"]) + BH / 2,
           arrow=False, op=".55", dash="4 4"))
    a(line(FAN, _y(po) + BH / 2, BX + BW + 2, _y(po) + BH / 2, op=".75"))
    a(txt(FAN + 14, _y(idx["design"]) + 18, T["f1_fan"], size=11.5, op=".7",
          anchor="start"))
    a(txt(FAN + 14, _y(idx["design"]) + 34, T["f1_fan2"], size=10.5, op=".55",
          anchor="start"))

    # proposed's returns, on the left
    a(line(BX, _y(po) + BH / 2, RET, _y(po) + BH / 2, arrow=False,
           op=".75", var="prop"))
    a(line(RET, _y(po) + BH / 2, RET, _y(idx["build"]) + 14, arrow=False,
           op=".75", var="prop"))
    for name, dy in (("build", 14), ("implement", 24), ("claim", 34)):
        a(line(RET, _y(idx[name]) + dy, BX - 2, _y(idx[name]) + dy, op=".75",
               var="prop"))
    a(line(RET, _y(idx["build"]) + 14, RET, _y(idx["claim"]) + 34,
           arrow=False, op=".75", var="prop"))
    ry = (_y(idx["build"]) + _y(idx["claim"])) / 2 + 24
    a(txt(RET - 14, ry, T["f1_ret1"], size=11.5, var="prop",
          transform="rotate(-90 %d %d)" % (RET - 14, ry)))
    for name, dy, key in (("build", 14, "f1_ret_build"),
                          ("implement", 24, "f1_ret_impl"),
                          ("claim", 34, "f1_ret_claim")):
        a(txt(RET + 8, _y(idx[name]) + dy - 5, T[key], size=10.5, anchor="start",
              op=".62"))

    # waiting on you — brass is only ever a person
    wy = _y(po) + BH + 16
    a(box(RX, wy, RW, BH, var="brass", sw=2))
    a(txt(RX + RW / 2, wy + 20, T["f1_wait"], size=13, mono=True, var="brass"))
    a(txt(RX + RW / 2, wy + 37, T["f1_wait2"], size=11, op=".62"))
    a(poly([(BX + BW, _y(po) + BH - 8), (FAN + 30, _y(po) + BH - 8),
            (FAN + 30, wy + BH / 2), (RX - 2, wy + BH / 2)]))
    a(txt(RX + RW / 2, wy - 8, T["f1_spent"], size=10.5, op=".62"))

    # and waiting reaches end, because end runs on every outcome
    ey = _y(idx["end"]) + BH / 2
    a(poly([(RX + RW / 2, wy + BH), (RX + RW / 2, ey), (BX + BW + 2, ey)],
           op=".55"))
    a(txt(RX + RW / 2 + 10, ey - 8, T["f1_closed"], size=10.5, op=".62",
          anchor="start"))

    return ('<svg viewBox="0 0 980 %d" role="img" aria-label="%s">%s</svg>'
            % (bottom + 28, T["f1_alt"], "".join(o)))


# ---------------------------------------------------------------------- page
def page(T, other):
    rows = "".join(
        f'<tr><td class="k">{a}</td><td>{b}</td><td class="who">{c}</td></tr>'
        for a, b, c in T["tbl"])
    return f"""<!doctype html>
<html lang="{T['lang']}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!--
{T['comment']}
-->
<title>{T['title']}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Serif:wght@500;600&display=swap">

{STYLE}
{EXTRA_CSS}
</head>
<body>
<div class="wrap">

  <header class="mast">
    <p class="eyebrow">{T['eyebrow']} · <a href="{other}">{T['otherlang']}</a></p>
    <h1>{T['h1']}</h1>
    <p class="sub">{T['sub']}</p>
  </header>

  <div class="thesis">
    <p>{T['th1']}</p>
    <p>{T['th2']}</p>
  </div>

  <section>
    <h2>{T['s1h']}</h2>
    <p class="lede">{T['s1l']}</p>
    <figure>
      <div class="canvas">{figure_one(T)}</div>
      <figcaption>{T['s1c']}</figcaption>
    </figure>
  </section>

  <section>
    <h2>{T['s2h']}</h2>
    <p class="lede">{T['s2l']}</p>
    <div class="tablewrap"><table>
      <thead><tr><th>{T['th_what']}</th><th>{T['th_who']}</th><th>{T['th_crit']}</th></tr></thead>
      <tbody>{rows}</tbody>
    </table></div>
  </section>

  <section>
    <h2>{T['s3h']}</h2>
    <p class="lede">{T['s3l']}</p>
<pre class="code">steps:
  claim:
    - <b>queue</b>: {{ kinds: [bug, feature], backoff: 1h }}
      <b>restarts</b>: 1        <span class="c">{T['c_restarts']}</span>
  admit:
    - <b>worktree</b>: {{ base: main }}
  prepared:
    - <b>run</b>: pnpm install
      timeout: 10m
  implement:
    - <b>agent</b>: claude-code
      turns: 150            <span class="c">{T['c_turns']}</span>
      wall:  1h             <span class="c">{T['c_wall']}</span>
      <b>rounds</b>: 3            <span class="c">{T['c_rounds']}</span>
  build:
    - <b>run</b>: pnpm typecheck &amp;&amp; pnpm test
  review:
    - <b>agent</b>: claude-code
</pre>
    <p>{T['s3p']}</p>
    <p>{T['s3p2']}</p>
  </section>

  <section>
    <h2>{T['s4h']}</h2>
    <p class="lede">{T['s4l']}</p>
    <p>{T['s4p']}</p>
    <p>{T['s4p2']}</p>
  </section>

  <section>
    <h2>{T['s5h']}</h2>
    <p class="lede">{T['s5l']}</p>
    <div class="prop">
      <h3>{T['prop_h']}</h3>
      <p>{T['prop1']}</p>
      <p>{T['prop2']}</p>
    </div>
    <div class="gap">
      <h3>{T['gap_h']}</h3>
      <p>{T['gap1']}</p>
      <p>{T['gap2']}</p>
    </div>
  </section>

  <footer>{T['foot']}</footer>

</div>
</body>
</html>
"""

ROOT = pathlib.Path(__file__).resolve().parent.parent
pathlib.Path(ROOT / "doc/the-pass.html").write_text(page(EN, "the-pass.zh.html"))
pathlib.Path(ROOT / "doc/the-pass.zh.html").write_text(page(ZH, "the-pass.html"))
print("wrote doc/the-pass.html and doc/the-pass.zh.html")
