# -*- coding: utf-8 -*-
"""Emit doc/the-pass.html and doc/the-pass.zh.html from one geometry.

    python3 scripts/the-pass.py

Both pages are self-contained by the rule architecture.html states of itself:
no build, no assets, no script. That rule is about the *published* file, and it
is what makes a hand-maintained pair go wrong — architecture.html and its
Chinese twin are 61KB each and drift is caught by nobody. So here the geometry
is written once, the words are written twice in EN and ZH below it, and neither
HTML file is edited by hand. Changing the drawing means changing this file and
running it.

The style block is read out of doc/architecture.html rather than copied, so the
two pages cannot fall out of the same design system either.
"""
import pathlib

ARCH = (pathlib.Path(__file__).resolve().parent.parent / "doc/architecture.html").read_text()
STYLE = ARCH[ARCH.index("<style>"):ARCH.index("</style>") + len("</style>")]

# the page adds two things architecture.html has no use for
EXTRA_CSS = """
<style>
  pre.code {
    margin: 26px 0 0;
    background: var(--raised);
    border: 1px solid var(--rule);
    border-left: 3px solid var(--flow);
    padding: 16px 20px;
    overflow-x: auto;
    font-family: var(--f-mono);
    font-size: 13.5px;
    line-height: 1.7;
  }
  pre.code .c { color: var(--faint); }
  pre.code b { color: var(--flow); font-weight: 500; }
</style>
"""

MONO = 'font-family="IBM Plex Mono, monospace"'

def marker():
    return ('<defs><marker id="ar" viewBox="0 0 10 10" refX="9" refY="5" '
            'markerWidth="7" markerHeight="7" orient="auto-start-reverse">'
            '<path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor"/></marker></defs>')

def box(x, y, w, h, *, stroke="currentColor", var=None, sw=1, dash=None, op=None):
    s = f'<rect x="{x}" y="{y}" width="{w}" height="{h}" fill="none" stroke="{stroke}"'
    if var:
        s += f' style="stroke:var(--{var})"'
    s += f' stroke-width="{sw}"'
    if dash:
        s += f' stroke-dasharray="{dash}"'
    if op:
        s += f' opacity="{op}"'
    return s + "/>"

def txt(x, y, t, *, size=12.5, anchor="middle", mono=False, var=None, op=None,
        ls=None, weight=None, transform=None):
    s = f'<text x="{x}" y="{y}" text-anchor="{anchor}" font-size="{size}"'
    if mono:
        s += " " + MONO
    s += ' fill="currentColor"'
    if var:
        s += f' style="fill:var(--{var})"'
    if op:
        s += f' opacity="{op}"'
    if ls:
        s += f' letter-spacing="{ls}"'
    if weight:
        s += f' font-weight="{weight}"'
    if transform:
        s += f' transform="{transform}"'
    return s + f">{t}</text>"

def line(x1, y1, x2, y2, *, arrow=True, op=".55", var=None, dash=None, sw=1):
    s = f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke="currentColor"'
    if var:
        s += f' style="stroke:var(--{var})"'
    s += f' stroke-width="{sw}" opacity="{op}"'
    if dash:
        s += f' stroke-dasharray="{dash}"'
    if arrow:
        s += ' marker-end="url(#ar)"'
    return s + "/>"

def poly(pts, *, arrow=True, op=".55", var=None):
    p = " ".join(f"{a},{b}" for a, b in pts)
    s = f'<polyline points="{p}" fill="none" stroke="currentColor"'
    if var:
        s += f' style="stroke:var(--{var})"'
    s += f' stroke-width="1" opacity="{op}"'
    if arrow:
        s += ' marker-end="url(#ar)"'
    return s + "/>"


# ------------------------------------------------------------------- the words
# Geometry is above; nothing below here knows a coordinate.
EN = dict(
    lang="en",
    otherlang="中文",
    title="The Pass and the Worktree",
    comment="""  The Pass and the Worktree — where a refusal goes, and what it costs.

  Drawn 2026-09-11 from doc/decisions/0039-the-worktree-is-the-whole-of-a-pass.md,
  which is accepted and not yet built. Unlike architecture.html, this page draws
  a decision rather than the code: the two places it differs from today are
  marked, and the risk the ADR could not close is marked too.

  Generated by scripts/the-pass.py, not hand-edited — the English and Chinese
  files share one geometry, so editing this file loses the change. It is still
  one self-contained file: no build, no assets, no script. The only thing it
  fetches is the typeface.""",
    eyebrow="Lingtai · 灵台 — one pass, end to end",
    h1="The Pass and the Worktree",
    sub="A pass is what one claim buys: a branch, an agent, five gate points and a "
        "merge lane. This page draws where a refusal goes — and what "
        "<a href=\"decisions/0039-the-worktree-is-the-whole-of-a-pass.md\">0039</a> "
        "changed about that.",
    th1="<b>The worktree is the whole of a pass.</b> Everything a refusal could be "
        "answered by — the branch, the build, the diff — is on disk while the pass "
        "runs. <code>Effect.scoped</code> moves out to enclose the merge lane, so "
        "that stays true until the pass ends, and <i>a new run</i> stops being the "
        "answer to anything except a run that ended.",
    th2="<b>Any refusal returns to the agent, carrying its own evidence.</b> "
        "Findings, the build's output, the conflicting paths: three prompts "
        "differing in one argument, not three flows. A person is asked when "
        "<code>runtime.limits.rounds</code> is spent — and only then.",

    s1h="One pass, and where a refusal goes",
    s1l="Node names are the section comments in <code>run-once.ts</code>; the gate "
        "points and their actions are <code>.lingtai/config.yaml</code>, verbatim.",
    s1c="<b>Five gate points, and three of them run here.</b> <code>admit</code> and "
        "<code>merge</code> are declared with no actions, and "
        "<a href=\"decisions/0016-the-settled-model.md\">0016</a> §4 is why they are "
        "drawn at all: an unconfigured point renders <i>skipped</i>, never omitted. "
        "The dashed rectangle is the worktree's scope — 0039 §1 moves its lower edge "
        "past the merge lane, and that one move is the whole of the change. Brass is "
        "used for one thing on this page and on the board alike: a human is being "
        "waited on.",

    s2h="Three refusals, and what each one can prove",
    s2l="0038 gave a refused review its own purse because a shared ceiling is a race. "
        "That was right and stopped short: it drew the line between <i>kinds of "
        "failure</i>, when the line that matters is who authored the evidence.",
    th_what="what refused",
    th_who="who wrote the evidence",
    th_crit="the criterion",
    th_fake="can the fixer fake it",
    tbl=[
        ("a finding", "an agent, in prose",
         "another agent judges whether the scenario still happens",
         "yes — delete the line, rename the symbol"),
        ("a red build", "the compiler, the test",
         "<b>run it again; green is green</b>",
         "only by deleting the test"),
        ("a conflict", "git, naming the files",
         "the merge succeeds and the build stays green", "no"),
    ],
    s2c="<b><i>Make it green again</i> is free, machine-checked, and cannot be "
        "authored by the thing being checked</b> — which is what 0038 §2's guard was "
        "reaching for when it refused to buy a fixer for a refusal carrying no "
        "<code>findings</code>. It mistook <i>no findings field</i> for <i>no "
        "acceptance criterion</i>. A red build has one, and a stronger one.",

    f2_today="TODAY",
    f2_0039="0039 · ACCEPTED, NOT YET BUILT",
    f2_r1="review refuses, with findings",
    f2_r2="build goes red",
    f2_r3="the lane hits a conflict",
    f2_same="the same worktree",
    f2_new="a whole new run",
    f2_rounds="bounded by limits.rounds",
    f2_alt="Today, a refused review returns to the same worktree while a red build "
           "and a conflict each cost a whole new run. Under 0039 all three return to "
           "the same worktree, bounded by limits.rounds.",

    s3h="What one pass may spend",
    s3l="Three numbers in one block, because two of them already had to agree with a "
        "third kept somewhere else.",
    c_turns="# inside one agent run",
    c_wall="# inside one agent run",
    c_rounds="# how many times a pass sends the agent back",
    s3p="<code>round</code> is the word the code already speaks — "
        "<code>FixRequested.round</code>, <code>roundsSpent</code>, <i>round 1 of 2</i>. "
        "It is not <code>attempts</code>, which already means two other things: "
        "<code>budget.attempts</code> is how much history a prompt carries, and an "
        "<i>attempt</i> on the board is a claim. Putting it beside <code>turns</code> "
        "and <code>wall</code> is the point rather than tidiness: what one pass may "
        "spend is then one block, <code>(rounds + 1) × wall</code>. On 2026-09-10 the "
        "drain told an operator it would wait at most one <code>wall</code>, which the "
        "fix loop had already made false — a sentence chasing a number kept elsewhere. "
        "Three numbers in one place cannot drift apart like that. "
        "<code>repair.maxAttempts</code> and <code>repair.fix</code> are what "
        "<code>rounds</code> now counts, and <code>repair.on</code> is "
        "<code>rounds: 0</code>.",

    s4h="Where this page is ahead of the code, and where the risk is",
    prop_h="Not yet built",
    prop1="Today only a refused <code>review</code> returns to the agent. A red "
          "<code>build</code> walks on to the merge lane carrying a "
          "<code>gate-failed</code> verdict, and a conflict aborts the lane; both "
          "then reach <code>decideRepair</code>, which buys an agent for a <b>new "
          "run</b> — because the worktree was released before the integrator ran.",
    prop2="Which is to say the expensive path was never a decision about failures. "
          "It was an ordering between two scopes, and §1 is the whole of undoing it.",
    gap_h="The risk lives in an unwritten reason",
    gap1="<code>run-once.ts:53</code> says <i>the worktree is gone before the "
         "integrator runs, because the integrator is outside its scope</i>. "
         "<b>That <i>because</i> is circular</b> — nothing records why the integrator "
         "was put outside the scope in the first place.",
    gap2="So whoever implements §1 has to go looking for what breaks when a worktree "
         "outlives the lane, rather than reading the silence as evidence that nothing "
         "does. The rest of 0039 is bookkeeping; this is where it can be wrong.",

    f1_claim="recipe · env · tier · claim",
    f1_admit="nothing configured — renders skipped",
    f1_scope="THE WORKTREE'S SCOPE · 0039 §1 MOVES THIS LOWER EDGE PAST THE MERGE LANE",
    f1_worktree="worktree · the hook, proven to fail closed",
    f1_prepared="install",
    f1_agent="the agent · Runtime.run",
    f1_agent2="one worktree, every round",
    f1_proposed="build, then review",
    f1_merge="nothing configured — renders skipped",
    f1_pass="passes",
    f1_nothold="nothing held",
    f1_lane="the merge lane · the base comes in first",
    f1_lane2="the advisory lock and its own worktree are one scope",
    f1_ret1="a refusal returns here",
    f1_ret2="findings · build output · conflicting paths",
    f1_wait="waiting on you",
    f1_wait2="a disagreement, or a human: action",
    f1_spent="rounds spent",
    f1_held="held",
    f1_landed="landed",
    f1_landed2="merged into the base",
    f1_merged="merged",
    f1_end="close the ticket · labels · runs on every outcome",
    f1_alt="One pass from claim to end. Five gate points on a spine: admit and merge "
           "are declared but empty, prepared, proposed and end run actions. A dashed "
           "rectangle marks the worktree's scope and encloses everything from the "
           "worktree through the merge lane. Both the proposed point and the merge "
           "lane feed a single return channel back into the agent, which sits in the "
           "same worktree. Waiting on a person and landed both reach the end point.",

    foot="Drawn 2026-09-11 at <code>cb66466</code>, from the ADR rather than the code. "
         "See <a href=\"architecture.html\">The Loop and the Log</a> for which process "
         "any of this runs in, and "
         "<a href=\"decisions/0039-the-worktree-is-the-whole-of-a-pass.md\">0039</a> "
         "for the argument.",
)

ZH = dict(
    lang="zh",
    otherlang="English",
    title="一趟 pass 与工作树",
    comment="""  一趟 pass 与工作树 —— 一次拒绝去哪里，代价是什么。

  2026-09-11 依据 doc/decisions/0039-the-worktree-is-the-whole-of-a-pass.md 绘制。
  该决定已接受，尚未实现。与 architecture.html 不同，这张图画的是决定而不是代码：
  两处与今天不同的地方都标了出来，ADR 没能关掉的那个风险也标了出来。

  由 scripts/the-pass.py 生成，不手工编辑 —— 中英两份共用同一套几何，
  直接改这个文件会丢掉改动。它仍然是一个自足的文件：不需要构建，没有资源，
  没有脚本。只取一次字体。""",
    eyebrow="Lingtai · 灵台 —— 一趟 pass，从头到尾",
    h1="一趟 pass 与工作树",
    sub="一趟 pass 就是一次 claim 买到的东西：一个分支、一个 agent、五个 gate 点，"
        "外加一条合并道。这张图画的是一次拒绝去哪里，以及 "
        "<a href=\"decisions/0039-the-worktree-is-the-whole-of-a-pass.md\">0039</a> "
        "把它改成了什么。",
    th1="<b>工作树就是一趟 pass 的全部现场。</b>回答一次拒绝所需要的一切 —— 分支、"
        "构建产物、那份 diff —— 在这趟 pass 跑着的时候都还在磁盘上。"
        "<code>Effect.scoped</code> 外扩到把合并道也包进去，于是这句话到这趟 pass "
        "结束都成立，而<i>开新的一趟 run</i> 不再是任何问题的答案 —— 除了一趟真的"
        "结束了的 run。",
    th2="<b>任何拒绝都带着自己的证据回到 agent。</b>findings、build 的输出、"
        "冲突的路径：三个 prompt 只差一个参数，不是三条流程。"
        "只有 <code>runtime.limits.rounds</code> 用尽，才去问人。",

    s1h="一趟 pass，以及一次拒绝去哪里",
    s1l="节点名取自 <code>run-once.ts</code> 的分节注释；gate 点和动作名取自 "
        "<code>.lingtai/config.yaml</code>，都是原样。",
    s1c="<b>五个 gate 点，这里执行的是三个。</b><code>admit</code> 和 "
        "<code>merge</code> 声明了但没有动作，而 "
        "<a href=\"decisions/0016-the-settled-model.md\">0016</a> §4 正是它们仍然"
        "被画出来的原因：一个没有配置的点渲染成 <i>skipped</i>，绝不省略。虚线框"
        "是工作树的作用域 —— 0039 §1 把它的下边缘移到合并道之后，整个改动就是这一步。"
        "黄铜色在这一页和看板上都只表示一件事：正在等人。",

    s2h="三种拒绝，各自能证明什么",
    s2l="0038 给被拒的 review 单独一个钱包，理由是共用上限是一场赛跑。这个论证是对的，"
        "但没走到头：它把线划在<i>失败的种类</i>之间，而真正要紧的线是谁写下了那份证据。",
    th_what="什么拒绝的",
    th_who="证据是谁写的",
    th_crit="判据",
    th_fake="修的 agent 能伪造吗",
    tbl=[
        ("finding", "一个 agent，用散文写的",
         "另一个 agent 判断那个场景是否还会发生",
         "能 —— 删掉那行、把符号改个名"),
        ("build 红了", "编译器、测试",
         "<b>再跑一遍；绿就是绿</b>",
         "只能靠删掉测试"),
        ("冲突", "git，并点名了文件",
         "合并成功，并且 build 仍然是绿的", "不能"),
    ],
    s2c="<b><i>让它重新变绿</i>不要钱、由机器检查，而且无法由被检查的那一方写出来</b> —— "
        "这正是 0038 §2 那道防线想要的东西：它拒绝为一个不带 <code>findings</code> 的"
        "拒绝买 fixer。它把<i>没有 findings 字段</i>错当成了<i>没有验收标准</i>。"
        "一个红的 build 有验收标准，而且更硬。",

    f2_today="今天",
    f2_0039="0039 · 已接受，尚未实现",
    f2_r1="review 拒绝，带着 findings",
    f2_r2="build 变红",
    f2_r3="合并道撞上冲突",
    f2_same="同一个工作树",
    f2_new="整整一趟新的 run",
    f2_rounds="由 limits.rounds 封顶",
    f2_alt="今天，被拒的 review 回到同一个工作树，而红的 build 和冲突各自要花掉整整"
           "一趟新的 run。0039 之后三者都回到同一个工作树，由 limits.rounds 封顶。",

    s3h="一趟 pass 最多花多少",
    s3l="三个数放在同一个块里，因为其中两个本来就得和另一个放在别处的数保持一致。",
    c_turns="# 一次 agent run 之内",
    c_wall="# 一次 agent run 之内",
    c_rounds="# 一趟 pass 把 agent 打回去几次",
    s3p="<code>round</code> 是代码里已经在说的词 —— <code>FixRequested.round</code>、"
        "<code>roundsSpent</code>、<i>round 1 of 2</i>。不是 <code>attempts</code>，"
        "那个词已经有两个别的意思了：<code>budget.attempts</code> 是一个 prompt 带多少"
        "历史，看板上的一次 <i>attempt</i> 是一次 claim。把它摆在 <code>turns</code> 和 "
        "<code>wall</code> 旁边是目的本身，不是为了整齐：一趟 pass 最多花多少，从此就是"
        "一个块，<code>(rounds + 1) × wall</code>。2026-09-10 那天，排空提示告诉操作者"
        "最多等一个 <code>wall</code> —— 而修复循环早就让这句话不成立了，一句话在追一个"
        "存在别处的数。三个数在同一处，就没法这样各自漂移。"
        "<code>repair.maxAttempts</code> 和 <code>repair.fix</code> 就是 "
        "<code>rounds</code> 现在数的东西，<code>repair.on</code> 就是 "
        "<code>rounds: 0</code>。",

    s4h="这一页比代码超前在哪，风险又在哪",
    prop_h="尚未实现",
    prop1="今天只有被拒的 <code>review</code> 会回到 agent。红的 <code>build</code> "
          "会带着 <code>gate-failed</code> 的裁决继续走到合并道；冲突则让合并道 abort。"
          "两者随后都走到 <code>decideRepair</code>，由它买一个 agent 开<b>新的一趟 "
          "run</b> —— 因为工作树在 integrator 跑起来之前就被释放了。",
    prop2="也就是说，那条昂贵的路径从来不是一个关于失败的决定。它是两个作用域之间的一个"
          "次序，而 §1 就是把这个次序整个撤掉。",
    gap_h="风险全在一个没写下来的理由里",
    gap1="<code>run-once.ts:53</code> 说：<i>工作树在 integrator 跑起来之前就没了，"
         "因为 integrator 在它的作用域之外</i>。<b>这个「因为」是循环的</b> —— "
         "没有任何地方记下当初为什么把 integrator 放到作用域之外。",
    gap2="所以实现 §1 的人必须去找：当工作树活得比合并道更久时，什么会坏掉 —— 而不是"
         "把这份沉默当成「什么都不会坏」的证据。0039 剩下的部分都是记账；能出错的是这里。",

    f1_claim="recipe · env · tier · claim",
    f1_admit="没有配置动作 —— 渲染成 skipped",
    f1_scope="工作树的作用域 · 0039 §1 把下边缘移到合并道之后",
    f1_worktree="worktree · 证明过会 fail closed 的 hook",
    f1_prepared="install",
    f1_agent="the agent · Runtime.run",
    f1_agent2="一个工作树，每一轮都是它",
    f1_proposed="先 build，再 review",
    f1_merge="没有配置动作 —— 渲染成 skipped",
    f1_pass="通过",
    f1_nothold="没有要问人的",
    f1_lane="合并道 · 先把 base 合进来",
    f1_lane2="advisory lock 和它自己的工作树是同一个作用域",
    f1_ret1="一次拒绝回到这里",
    f1_ret2="findings · build 输出 · 冲突的路径",
    f1_wait="等你",
    f1_wait2="两个 agent 有分歧，或 human: 动作",
    f1_spent="rounds 用尽",
    f1_held="被拦下",
    f1_landed="已落地",
    f1_landed2="并进了 base",
    f1_merged="合上了",
    f1_end="关掉 ticket · 打标签 · 每种结局都会跑",
    f1_alt="一趟 pass，从 claim 到 end。主干上五个 gate 点：admit 和 merge 声明了但"
           "是空的，prepared、proposed 和 end 会执行动作。一个虚线矩形标出工作树的"
           "作用域，把从工作树一直到合并道的全部包了进去。proposed 点和合并道都汇入"
           "同一条返回通道，回到那个仍在同一个工作树里的 agent。等你和已落地两种结局"
           "都走到 end 点。",

    foot="2026-09-11 在 <code>cb66466</code> 绘制，依据的是 ADR 而不是代码。"
         "想知道这些各自跑在哪个进程里，看 "
         "<a href=\"architecture.zh.html\">循环与日志</a>；想看论证，看 "
         "<a href=\"decisions/0039-the-worktree-is-the-whole-of-a-pass.md\">0039</a>。",
)


# ---------------------------------------------------------------- figure one
CX, BX, BW = 460, 280, 360     # spine
RX, RW = 690, 220              # the right-hand column
CH = 170                       # the return channel
JOIN = 940                     # the join into `end`

def figure_one(T):
    o = [marker()]
    a = o.append

    def labelled(y, h, l1, l2=None, **kw):
        a(box(BX, y, BW, h, **kw))
        if l2 is None:
            a(txt(CX, y + h / 2 + 4.5, l1, size=13))
        else:
            a(txt(CX, y + 21, l1, size=13))
            a(txt(CX, y + 38, l2, size=11.5, op=".62"))

    def gate(y, n, name, actions, live):
        h = 46
        if live:
            a(box(BX, y, BW, h, var="flow", sw=2))
        else:
            a(box(BX, y, BW, h, var="faint", sw=1.5, dash="5 4", op=".85"))
        a(txt(BX + 16, y + 20, n, size=11, mono=True, anchor="start",
              var="flow" if live else "faint", ls="1.2"))
        a(txt(CX, y + 20, name, size=13, mono=True))
        a(txt(CX, y + 37, actions, size=11.5, op=".62"))

    # above the scope
    labelled(26, 38, T["f1_claim"])
    a(line(CX, 64, CX, 82))
    gate(84, "1/5", "admit", T["f1_admit"], False)
    a(line(CX, 130, CX, 184))

    # the scope
    a(box(40, 150, 890, 440, var="prop", sw=2, dash="7 5"))
    a(txt(56, 172, T["f1_scope"], size=11, mono=True, anchor="start",
          var="prop", ls="1.3"))

    labelled(186, 40, T["f1_worktree"])
    a(line(CX, 226, CX, 244))
    gate(246, "2/5", "prepared", T["f1_prepared"], True)
    a(line(CX, 292, CX, 312))

    # the agent — the strongest box on the page
    a(box(BX, 314, BW, 54, sw=2.5))
    a(txt(CX, 338, T["f1_agent"], size=14, mono=True))
    a(txt(CX, 356, T["f1_agent2"], size=11.5, op=".62"))

    a(line(CX, 368, CX, 390))
    gate(392, "3/5", "proposed", T["f1_proposed"], True)
    a(line(CX, 438, CX, 460))
    a(txt(CX + 12, 453, T["f1_pass"], size=11, anchor="start", op=".6"))
    gate(462, "4/5", "merge", T["f1_merge"], False)
    a(line(CX, 508, CX, 526))
    a(txt(CX + 12, 521, T["f1_nothold"], size=11, anchor="start", op=".6"))

    labelled(528, 46, T["f1_lane"], T["f1_lane2"])

    # the return channel: both refusals, one destination
    a(line(BX, 415, CH, 415, arrow=False, op=".75", var="prop"))
    a(line(BX, 551, CH, 551, arrow=False, op=".75", var="prop"))
    a(line(CH, 551, CH, 341, arrow=False, op=".75", var="prop"))
    a(line(CH, 341, BX - 2, 341, op=".75", var="prop"))
    a(txt(158, 455, T["f1_ret1"], size=11.5, var="prop",
          transform="rotate(-90 158 455)"))
    a(txt(141, 455, T["f1_ret2"], size=10.5, var="prop", op=".8",
          transform="rotate(-90 141 455)"))

    # waiting on a person — brass, and brass is only ever that
    a(box(RX, 392, RW, 46, var="brass", sw=2))
    a(txt(RX + RW / 2, 412, T["f1_wait"], size=13, mono=True, var="brass"))
    a(txt(RX + RW / 2, 429, T["f1_wait2"], size=11, op=".62"))
    a(line(640, 415, RX - 2, 415))
    a(txt(RX + RW / 2, 384, T["f1_spent"], size=10.5, op=".62"))
    a(poly([(640, 485), (676, 485), (676, 440)]))
    a(txt(682, 470, T["f1_held"], size=10.5, anchor="start", op=".62"))

    a(box(RX, 528, RW, 46, var="flow", sw=2))
    a(txt(RX + RW / 2, 548, T["f1_landed"], size=13, mono=True, var="flow"))
    a(txt(RX + RW / 2, 565, T["f1_landed2"], size=11, op=".62"))
    a(line(640, 551, RX - 2, 551))
    a(txt(652, 543, T["f1_merged"], size=10.5, anchor="start", op=".62"))

    # both outcomes reach end — the point runs on every outcome
    a(line(910, 415, JOIN, 415, arrow=False, op=".55"))
    a(line(910, 551, JOIN, 551, arrow=False, op=".55"))
    a(line(JOIN, 415, JOIN, 639, arrow=False, op=".55"))
    a(line(JOIN, 639, 644, 639, op=".55"))

    a(box(BX, 616, BW, 46, var="flow", sw=2))
    a(txt(BX + 16, 636, "5/5", size=11, mono=True, anchor="start",
          var="flow", ls="1.2"))
    a(txt(CX, 636, "end", size=13, mono=True))
    a(txt(CX, 653, T["f1_end"], size=11.5, op=".62"))

    return ('<svg viewBox="0 0 980 700" role="img" aria-label="%s">%s</svg>'
            % (T["f1_alt"], "".join(o)))


# ---------------------------------------------------------------- figure two
def figure_two(T):
    o = [marker()]
    a = o.append
    rows = [T["f2_r1"], T["f2_r2"], T["f2_r3"]]
    ys = [44, 104, 164]

    a(txt(20, 20, T["f2_today"], size=11, mono=True, anchor="start",
          var="faint", ls="1.3"))
    for y, r in zip(ys, rows):
        a(txt(20, y + 25, r, size=12.5, anchor="start"))
        a(line(210, y + 20, 248, y + 20))
    # review stays; the other two buy a whole new run
    a(box(250, ys[0], 190, 40, var="flow", sw=2))
    a(txt(345, ys[0] + 25, T["f2_same"], size=12, mono=True, var="flow"))
    for y in ys[1:]:
        a(box(250, y, 190, 40, var="gap", sw=2))
        a(txt(345, y + 25, T["f2_new"], size=12, mono=True, var="gap"))

    a(line(470, 10, 470, 220, arrow=False, op=".3", dash="4 4"))

    a(txt(510, 20, T["f2_0039"], size=11, mono=True, anchor="start",
          var="prop", ls="1.3"))
    for y, r in zip(ys, rows):
        a(txt(510, y + 25, r, size=12.5, anchor="start"))
    a(poly([(700, 64), (722, 64), (722, 124), (738, 124)]))
    a(line(700, 124, 738, 124))
    a(poly([(700, 184), (722, 184), (722, 124), (738, 124)]))
    a(box(740, 94, 190, 60, sw=2.5))
    a(txt(835, 118, T["f2_same"], size=12.5, mono=True))
    a(txt(835, 136, T["f2_rounds"], size=11, op=".62"))

    return ('<svg viewBox="0 0 940 230" role="img" aria-label="%s">%s</svg>'
            % (T["f2_alt"], "".join(o)))


# ---------------------------------------------------------------------- page
def page(T, other):
    f1, f2 = figure_one(T), figure_two(T)
    rows = "".join(
        f'<tr><td class="k">{a}</td><td>{b}</td><td>{c}</td><td class="who">{d}</td></tr>'
        for a, b, c, d in T["tbl"])
    return f"""<!doctype html>
<html lang="{T['lang']}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!--
{T['comment']}
-->
<title>{T['title']}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Mono:wght@400;500&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Serif:wght@500;600&display=swap">

{STYLE}
{EXTRA_CSS}
</head>
<body>
<div class="wrap">

  <header class="mast">
    <p class="eyebrow">{T['eyebrow']} · <a href="{other}">{T['otherlang']}</a></p>
    <h1>{T['h1']}</h1>
    <p class="sub">{T['sub']}</p>
  </header>

  <div class="thesis">
    <p>{T['th1']}</p>
    <p>{T['th2']}</p>
  </div>

  <section>
    <h2>{T['s1h']}</h2>
    <p class="lede">{T['s1l']}</p>
    <figure>
      <div class="canvas">{f1}</div>
      <figcaption>{T['s1c']}</figcaption>
    </figure>
  </section>

  <section>
    <h2>{T['s2h']}</h2>
    <p class="lede">{T['s2l']}</p>
    <div class="tablewrap"><table>
      <thead><tr><th>{T['th_what']}</th><th>{T['th_who']}</th><th>{T['th_crit']}</th><th>{T['th_fake']}</th></tr></thead>
      <tbody>{rows}</tbody>
    </table></div>
    <figure>
      <div class="canvas">{f2}</div>
      <figcaption>{T['s2c']}</figcaption>
    </figure>
  </section>

  <section>
    <h2>{T['s3h']}</h2>
    <p class="lede">{T['s3l']}</p>
<pre class="code">runtime:
  limits:
    turns: 150   <span class="c">{T['c_turns']}</span>
    wall:  1h    <span class="c">{T['c_wall']}</span>
    <b>rounds: 2</b>    <span class="c">{T['c_rounds']}</span>
</pre>
    <p>{T['s3p']}</p>
  </section>

  <section>
    <h2>{T['s4h']}</h2>
    <div class="prop">
      <h3>{T['prop_h']}</h3>
      <p>{T['prop1']}</p>
      <p>{T['prop2']}</p>
    </div>
    <div class="gap">
      <h3>{T['gap_h']}</h3>
      <p>{T['gap1']}</p>
      <p>{T['gap2']}</p>
    </div>
  </section>

  <footer>{T['foot']}</footer>

</div>
</body>
</html>
"""

ROOT = pathlib.Path(__file__).resolve().parent.parent
pathlib.Path(ROOT / "doc/the-pass.html").write_text(page(EN, "the-pass.zh.html"))
pathlib.Path(ROOT / "doc/the-pass.zh.html").write_text(page(ZH, "the-pass.html"))
print("wrote doc/the-pass.html and doc/the-pass.zh.html")
